import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faMoon,
  faSun,
  faWifi,
  faTriangleExclamation,
  faBolt,
  faLocationDot,
  faVolumeHigh,
  faMagnifyingGlass,
  faArrowTrendUp,
  faArrowTrendDown,
  faShield,
  faPeopleGroup,
  faXmark,
  faArrowDown,
  faGear,
  faLocationPin,
  faDollarSign,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCamera,
  faBell,
  faClock,
  faCircleCheck,
  faBuilding,
  faPenToSquare,
  faEye,
  faTrashCan,
  faCalendarDays,
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faMoon,
  faSun,
  faWifi,
  faTriangleExclamation,
  faCamera,
  faBolt,
  faBell,
  faLocationDot,
  faClock,
  faVolumeHigh,
  faMagnifyingGlass,
  faArrowTrendUp,
  faArrowTrendDown,
  faShield,
  faCircleCheck,
  faPeopleGroup,
  faXmark,
  faArrowDown,
  faGear,
  faBuilding,
  faLocationPin,
  faPenToSquare,
  faEye,
  faTrashCan,
  faCalendarDays,
  faDollarSign
);
